import type { Material, SurfaceFinish, EdgeProfile } from '@/types';

export const initialMaterials: Material[] = [
  {
    id: 1,
    name: 'Plano',
    display_name: 'Plano White',
    density: 2.7,
    cost_sqm: 220,
    texture: 'https://placehold.co/1024x1024/EAE6D9/9D998D.png',
    color: '#EAE6D9',
    // PBR Properties (default values for a polished stone)
    roughness: 0.15,
    metallic: 0.0,
    normalStrength: 1.0,
    displacementScale: 0.001,
    clearcoat: 0.2,
    ambientOcclusion: 0.5,
    // Additional properties
    category_id: 'marble',
    subcategory: 'White Marble',
    supplier: 'StoneCo',
    supplierSku: 'PL-WHT-001',
    origin: 'Italy',
    availability: 'in_stock',
    leadTimeDays: 7,
    tags: ['white', 'veined', 'luxury'],
    isFeatured: true,
  },
  {
    id: 2,
    name: 'Kirmenjak',
    display_name: 'Kirmenjak Grey',
    density: 2.65,
    cost_sqm: 180,
    texture: 'https://placehold.co/1024x1024/E1DCC5/A9A594.png',
    color: '#E1DCC5',
    // PBR Properties (default values for a honed stone)
    roughness: 0.4,
    metallic: 0.0,
    normalStrength: 0.8,
    displacementScale: 0.0005,
    clearcoat: 0.0,
    ambientOcclusion: 0.3,
    // Additional properties
    category_id: 'limestone',
    subcategory: 'Grey Limestone',
    supplier: 'StoneCo',
    supplierSku: 'KI-GRY-002',
    origin: 'Croatia',
    availability: 'in_stock',
    leadTimeDays: 5,
    tags: ['grey', 'uniform', 'popular'],
    isFeatured: false,
  },
  {
    id: 3,
    name: 'Visočan',
    display_name: 'Visočan Beige',
    density: 2.6,
    cost_sqm: 190,
    texture: 'https://placehold.co/1024x1024/DAD6CD/A4A097.png',
    color: '#DAD6CD',
    // PBR Properties (default values for a leathered stone)
    roughness: 0.6,
    metallic: 0.0,
    normalStrength: 0.7,
    displacementScale: 0.0008,
    clearcoat: 0.0,
    ambientOcclusion: 0.4,
    // Additional properties
    category_id: 'limestone',
    subcategory: 'Beige Limestone',
    supplier: 'StoneCo',
    supplierSku: 'VI-BEG-003',
    origin: 'Turkey',
    availability: 'in_stock',
    leadTimeDays: 6,
    tags: ['beige', 'textured', 'durable'],
    isFeatured: false,
  },
  {
    id: 4,
    name: 'Sivac',
    display_name: 'Sivac Gray',
    density: 2.67,
    cost_sqm: 210,
    texture: 'https://placehold.co/1024x1024/C7C7C7/8F8F8F.png',
    color: '#C7C7C7',
    // PBR Properties (default values for a flamed stone)
    roughness: 0.8,
    metallic: 0.0,
    normalStrength: 0.9,
    displacementScale: 0.0003,
    clearcoat: 0.0,
    ambientOcclusion: 0.2,
    // Additional properties
    category_id: 'granite',
    subcategory: 'Gray Granite',
    supplier: 'StoneCo',
    supplierSku: 'SI-GRY-004',
    origin: 'Spain',
    availability: 'in_stock',
    leadTimeDays: 8,
    tags: ['gray', 'speckled', 'outdoor'],
    isFeatured: false,
  },
  {
    id: 5,
    name: 'Kanfanar',
    display_name: 'Kanfanar Brown',
    density: 2.63,
    cost_sqm: 160,
    texture: 'https://placehold.co/1024x1024/DED9C4/A49E82.png',
    color: '#DED9C4',
    // PBR Properties (default values for a brushed stone)
    roughness: 0.5,
    metallic: 0.0,
    normalStrength: 0.75,
    displacementScale: 0.0006,
    clearcoat: 0.05,
    ambientOcclusion: 0.35,
    // Additional properties
    category_id: 'granite',
    subcategory: 'Brown Granite',
    supplier: 'StoneCo',
    supplierSku: 'KA-BRN-005',
    origin: 'Croatia',
    availability: 'in_stock',
    leadTimeDays: 4,
    tags: ['brown', 'veined', 'versatile'],
    isFeatured: false,
  },
  {
    id: 6,
    name: 'Avorio',
    display_name: 'Avorio Cream',
    density: 2.68,
    cost_sqm: 280,
    texture: 'https://placehold.co/1024x1024/FDF5E6/B0A492.png',
    color: '#FDF5E6',
    // PBR Properties (default values for a polished quartz)
    roughness: 0.1,
    metallic: 0.0,
    normalStrength: 0.9,
    displacementScale: 0.0002,
    clearcoat: 0.3,
    ambientOcclusion: 0.6,
    // Additional properties
    category_id: 'quartz',
    subcategory: 'Cream Quartz',
    supplier: 'StoneCo',
    supplierSku: 'AV-CRM-006',
    origin: 'Turkey',
    availability: 'in_stock',
    leadTimeDays: 10,
    tags: ['cream', 'uniform', 'low-maintenance'],
    isFeatured: true,
  },
  {
    id: 7,
    name: 'Pulenat',
    display_name: 'Pulenat Green',
    density: 2.64,
    cost_sqm: 200,
    texture: 'https://placehold.co/1024x1024/DCDCDC/A9A9A9.png',
    color: '#DCDCDC',
    // PBR Properties (default values for a honed quartz)
    roughness: 0.35,
    metallic: 0.0,
    normalStrength: 0.85,
    displacementScale: 0.0004,
    clearcoat: 0.0,
    ambientOcclusion: 0.4,
    // Additional properties
    category_id: 'quartz',
    subcategory: 'Green Quartz',
    supplier: 'StoneCo',
    supplierSku: 'PU-GRN-007',
    origin: 'Norway',
    availability: 'in_stock',
    leadTimeDays: 7,
    tags: ['green', 'uniform', 'modern'],
    isFeatured: false,
  },
  {
    id: 8,
    name: 'Lahor',
    display_name: 'Lahor Beige',
    density: 2.58,
    cost_sqm: 140,
    texture: 'https://placehold.co/1024x1024/FAF0E6/C3B091.png',
    color: '#FAF0E6',
    // PBR Properties (default values for a sandblasted limestone)
    roughness: 0.7,
    metallic: 0.0,
    normalStrength: 0.6,
    displacementScale: 0.0007,
    clearcoat: 0.0,
    ambientOcclusion: 0.25,
    // Additional properties
    category_id: 'limestone',
    subcategory: 'Beige Limestone',
    supplier: 'StoneCo',
    supplierSku: 'LA-BEG-008',
    origin: 'Turkey',
    availability: 'in_stock',
    leadTimeDays: 3,
    tags: ['beige', 'porous', 'affordable'],
    isFeatured: false,
  },
  {
    id: 9,
    name: 'Mironja',
    display_name: 'Mironja Dark Brown',
    density: 2.8,
    cost_sqm: 250,
    texture: 'https://placehold.co/1024x1024/D2B48C/8C7853.png',
    color: '#D2B48C',
    // PBR Properties (default values for a bush-hammered granite)
    roughness: 0.85,
    metallic: 0.0,
    normalStrength: 0.95,
    displacementScale: 0.0009,
    clearcoat: 0.0,
    ambientOcclusion: 0.15,
    // Additional properties
    category_id: 'granite',
    subcategory: 'Dark Brown Granite',
    supplier: 'StoneCo',
    supplierSku: 'MI-DBR-009',
    origin: 'Bosnia and Herzegovina',
    availability: 'limited',
    leadTimeDays: 14,
    tags: ['dark brown', 'rustic', 'textured'],
    isFeatured: false,
  },
  {
    id: 10,
    name: 'Botticino',
    display_name: 'Botticino Classic',
    density: 2.7,
    cost_sqm: 350,
    texture: 'https://placehold.co/1024x1024/E6DCC9/B9A793.png',
    color: '#E6DCC9',
    // PBR Properties (default values for a polished marble)
    roughness: 0.12,
    metallic: 0.0,
    normalStrength: 0.95,
    displacementScale: 0.0005,
    clearcoat: 0.25,
    ambientOcclusion: 0.55,
    // Additional properties
    category_id: 'marble',
    subcategory: 'Classic Marble',
    supplier: 'StoneCo',
    supplierSku: 'BO-CLC-010',
    origin: 'Italy',
    availability: 'in_stock',
    leadTimeDays: 12,
    tags: ['classic', 'veined', 'premium'],
    isFeatured: true,
  },
  {
    id: 11,
    name: 'Carrara C',
    display_name: 'Carrara Carrara',
    density: 2.71,
    cost_sqm: 450,
    texture: 'https://placehold.co/1024x1024/F5F5F5/CCCCCC.png',
    color: '#F5F5F5',
    // PBR Properties (default values for a polished Carrara marble)
    roughness: 0.08,
    metallic: 0.0,
    normalStrength: 0.98,
    displacementScale: 0.0003,
    clearcoat: 0.3,
    ambientOcclusion: 0.6,
    // Additional properties
    category_id: 'marble',
    subcategory: 'Carrara Marble',
    supplier: 'StoneCo',
    supplierSku: 'CR-CRR-011',
    origin: 'Italy',
    availability: 'in_stock',
    leadTimeDays: 18,
    tags: ['carrara', 'luxury', 'high-end'],
    isFeatured: true,
  },
];

export const initialSurfaceFinishes: SurfaceFinish[] = [
  { id: 0, name: 'Bez obrade', cost_sqm: 0 },
  { id: 1, name: 'Poliranje (Polished)', cost_sqm: 15 },
  { id: 2, name: 'Brušenje (Honed)', cost_sqm: 12 },
  { id: 3, name: 'Četkanje (Brushed)', cost_sqm: 18 },
  { id: 4, name: 'Paljenje (Flamed)', cost_sqm: 20 },
  { id: 5, name: 'Pjeskarenje (Sandblasted)', cost_sqm: 22 },
  { id: 6, name: 'Bućardanje (Bush-hammered)', cost_sqm: 25 },
  { id: 7, name: 'Štokovanje (Tooled)', cost_sqm: 23 },
  { id: 8, name: 'Antico (Antiqued)', cost_sqm: 28 },
  { id: 9, name: 'Martelina (Martellina)', cost_sqm: 20 },
  { id: 10, name: 'Pilano (Sawn)', cost_sqm: 5 },
];

export const initialEdgeProfiles: EdgeProfile[] = [
  { id: 1, name: 'Ravni rez (Pilan)', cost_m: 2 },
  { id: 10, name: 'Smuš C0.5 (0.5mm 45°)', cost_m: 5 },
  { id: 11, name: 'Smuš C1 (1mm 45°)', cost_m: 7 },
  { id: 12, name: 'Smuš C2 (2mm 45°)', cost_m: 8 },
  { id: 13, name: 'Smuš C5 (5mm 45°)', cost_m: 10 },
  { id: 14, name: 'Smuš C7 (7mm 45°)', cost_m: 11 },
  { id: 15, name: 'Smuš C8 (8mm 45°)', cost_m: 12 },
  { id: 16, name: 'Smuš C10 (10mm 45°)', cost_m: 13 },
  { id: 20, name: 'Puno-zaobljena R1cm', cost_m: 12 },
  { id: 21, name: 'Puno-zaobljena R1.5cm', cost_m: 15 },
  { id: 22, name: 'Puno-zaobljena R2cm', cost_m: 18 },
  { id: 30, name: 'Puno-zaobljena R1.5cm (Half Bullnose)', cost_m: 20 },
  { id: 31, name: 'Puno-zaobljena R2cm (Half Bullnose)', cost_m: 25 },
  { id: 40, name: 'T-profil', cost_m: 35 },
  { id: 41, name: 'Dupli T-profil', cost_m: 45 },
];
